# Generated by Django 2.1.5 on 2019-02-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen_layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridge_brand', models.TextField()),
                ('range_brand', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
